var k;k||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(b,a)=>{throw a;},ea="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var p="",fa,q;
if(ca){var fs=require("fs");p=__dirname+"/";q=b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b)};fa=async b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{p=(new URL(".",ea)).href}catch{}ba&&(q=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});fa=async b=>{if(t(b))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var z=console.error.bind(console),A,ha=!1,t=b=>b.startsWith("file://"),ia,ja,B,C,E,F,G,ka,la,ma,na,J=0,K=null;
function oa(b){k.onAbort?.(b);b="Aborted("+b+")";z(b);ha=!0;throw new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");}var pa;async function qa(b){if(!A)try{var a=await fa(b);return new Uint8Array(a)}catch{}if(b==pa&&A)b=new Uint8Array(A);else if(q)b=q(b);else throw"both async and sync fetching of the wasm failed";return b}async function ra(b,a){try{var c=await qa(b);return await WebAssembly.instantiate(c,a)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(b){var a=pa;if(!A&&!t(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ra(a,b)}class ta{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var ua=b=>{for(;0<b.length;)b.shift()(k)},va=[],wa=[],xa=()=>{var b=k.preRun.shift();wa.push(b)},za=!0;
class Aa{constructor(b){this.F=b-24}}var Ba=0,Ca=0,L=b=>{for(var a="";;){var c=B[b++];if(!c)return a;a+=String.fromCharCode(c)}},M={},N={},O={},P=class extends Error{constructor(b){super(b);this.name="BindingError"}},Da=b=>{throw new P(b);};
function Ea(b,a,c={}){var d=a.name;if(!b)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(b)){if(c.ia)return;throw new P(`Cannot register type '${d}' twice`);}N[b]=a;delete O[b];M.hasOwnProperty(b)&&(a=M[b],delete M[b],a.forEach(e=>e()))}function Q(b,a,c={}){return Ea(b,a,c)}
var Fa=(b,a,c)=>{switch(a){case 1:return c?d=>ja[d]:d=>B[d];case 2:return c?d=>C[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ga=b=>{throw new P(b.C.G.D.name+" instance already deleted");},Ha=!1,Ia=()=>{},R=b=>{if("undefined"===typeof FinalizationRegistry)return R=a=>a,b;Ha=new FinalizationRegistry(a=>{a=a.C;--a.count.value;0===a.count.value&&(a.J?a.M.R(a.J):a.G.D.R(a.F))});R=a=>
{var c=a.C;c.J&&Ha.register(a,{C:c},a);return a};Ia=a=>{Ha.unregister(a)};return R(b)},Ja=[];function S(){}
var Ka=(b,a)=>Object.defineProperty(a,"name",{value:b}),La={},Ma=(b,a,c)=>{if(void 0===b[a].I){var d=b[a];b[a]=function(...e){if(!b[a].I.hasOwnProperty(e.length))throw new P(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].I})!`);return b[a].I[e.length].apply(this,e)};b[a].I=[];b[a].I[d.T]=d}},Na=(b,a,c)=>{if(k.hasOwnProperty(b)){if(void 0===c||void 0!==k[b].I&&void 0!==k[b].I[c])throw new P(`Cannot register public name '${b}' twice`);Ma(k,b,b);if(k[b].I.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[b].I[c]=a}else k[b]=a,k[b].T=c},Oa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Pa(b,a,c,d,e,f,h,g){this.name=b;this.constructor=a;this.P=c;this.R=d;this.K=e;this.ga=f;this.W=h;this.fa=g;this.ka=[]}
var T=(b,a,c)=>{for(;a!==c;){if(!a.W)throw new P(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.W(b);a=a.K}return b},Qa=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Ra(b,a){if(null===a){if(this.Z)throw new P(`null is not a valid ${this.name}`);return 0}if(!a.C)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);return T(a.C.F,a.C.G.D,this.D)}
function Sa(b,a){if(null===a){if(this.Z)throw new P(`null is not a valid ${this.name}`);if(this.Y){var c=this.la();null!==b&&b.push(this.R,c);return c}return 0}if(!a||!a.C)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.X&&a.C.G.X)throw new P(`Cannot convert argument of type ${a.C.M?a.C.M.name:a.C.G.name} to parameter type ${this.name}`);c=T(a.C.F,a.C.G.D,this.D);if(this.Y){if(void 0===a.C.J)throw new P("Passing raw pointer to smart pointer is illegal");
switch(this.na){case 0:if(a.C.M===this)c=a.C.J;else throw new P(`Cannot convert argument of type ${a.C.M?a.C.M.name:a.C.G.name} to parameter type ${this.name}`);break;case 1:c=a.C.J;break;case 2:if(a.C.M===this)c=a.C.J;else{var d=a.clone();c=this.ma(c,Ta(()=>d["delete"]()));null!==b&&b.push(this.R,c)}break;default:throw new P("Unsupporting sharing policy");}}return c}
function Ua(b,a){if(null===a){if(this.Z)throw new P(`null is not a valid ${this.name}`);return 0}if(!a.C)throw new P(`Cannot pass "${Qa(a)}" as a ${this.name}`);if(!a.C.F)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.C.G.X)throw new P(`Cannot convert argument of type ${a.C.G.name} to parameter type ${this.name}`);return T(a.C.F,a.C.G.D,this.D)}function Va(b){return this.H(G[b>>2])}
var Wa=(b,a,c)=>{if(a===c)return b;if(void 0===c.K)return null;b=Wa(b,a,c.K);return null===b?null:c.fa(b)},Xa={},Ya=(b,a)=>{if(void 0===a)throw new P("ptr should not be undefined");for(;b.K;)a=b.W(a),b=b.K;return Xa[a]},Za=class extends Error{constructor(b){super(b);this.name="InternalError"}},$a=(b,a)=>{if(!a.G||!a.F)throw new Za("makeClassHandle requires ptr and ptrType");if(!!a.M!==!!a.J)throw new Za("Both smartPtrType and smartPtr must be specified");a.count={value:1};return R(Object.create(b,
{C:{value:a,writable:!0}}))};function ab(b,a,c,d,e,f,h,g,l,n,m){this.name=b;this.D=a;this.Z=c;this.X=d;this.Y=e;this.ja=f;this.na=h;this.da=g;this.la=l;this.ma=n;this.R=m;e||void 0!==a.K?this.L=Sa:(this.L=d?Ra:Ua,this.N=null)}
var bb=(b,a,c)=>{if(!k.hasOwnProperty(b))throw new Za("Replacing nonexistent public symbol");void 0!==k[b].I&&void 0!==c?k[b].I[c]=a:(k[b]=a,k[b].T=c)},cb=[],db,U=(b,a)=>{b=L(b);var c;(c=cb[a])||(cb[a]=c=db.get(a));if("function"!=typeof c)throw new P(`unknown function pointer with signature ${b}: ${a}`);return c};class eb extends Error{}
var hb=b=>{b=fb(b);var a=L(b);V(b);return a},W=(b,a)=>{function c(f){e[f]||N[f]||(O[f]?O[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new eb(`${b}: `+d.map(hb).join([", "]));},X=(b,a,c)=>{function d(g){g=c(g);if(g.length!==b.length)throw new Za("Mismatched type converter count");for(var l=0;l<b.length;++l)Q(b[l],g[l])}b.forEach(g=>O[g]=a);var e=Array(a.length),f=[],h=0;a.forEach((g,l)=>{N.hasOwnProperty(g)?e[l]=N[g]:(f.push(g),M.hasOwnProperty(g)||(M[g]=[]),M[g].push(()=>{e[l]=
N[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},ib=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c},jb=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function kb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].N)return!0;return!1}
function lb(b,a,c,d,e,f){var h=a.length;if(2>h)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==a[1]&&null!==c,l=kb(a);c=!a[0].ba;var n=a[0],m=a[1];d=[b,Da,d,e,jb,n.H.bind(n),m?.L.bind(m)];for(e=2;e<h;++e)n=a[e],d.push(n.L.bind(n));if(!l)for(e=g?1:2;e<a.length;++e)null!==a[e].N&&d.push(a[e].N);l=kb(a);e=a.length-2;m=[];n=["fn"];g&&n.push("thisWired");for(h=0;h<e;++h)m.push(`arg${h}`),n.push(`arg${h}Wired`);m=m.join(",");n=n.join(",");m=`return function (${m}) {\n`;
l&&(m+="var destructors = [];\n");var u=l?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(m+=`var thisWired = toClassParamWire(${u}, this);\n`);for(h=0;h<e;++h){var r=`toArg${h}Wire`;m+=`var arg${h}Wired = ${r}(${u}, arg${h});\n`;w.push(r)}m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(h=g?1:2;h<a.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].N&&(m+=`${f}_dtor(${f});\n`,
w.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(w,m+"}\n"))(...d);return Ka(b,a)}
var mb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},nb=(b,a,c)=>{if(!(b instanceof Object))throw new P(`${c} with invalid "this": ${b}`);if(!(b instanceof a.D.constructor))throw new P(`${c} incompatible with "this" of type ${b.constructor.name}`);if(!b.C.F)throw new P(`cannot call emscripten binding method ${c} on deleted object`);return T(b.C.F,b.C.G.D,a.D)},ob=[],Y=[0,1,,1,null,1,!0,1,!1,1],pb=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,ob.push(b))},qb=b=>{if(!b)throw new P(`Cannot use deleted val. handle = ${b}`);
return Y[b]},Ta=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=ob.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},rb={name:"emscripten::val",H:b=>{var a=qb(b);pb(b);return a},L:(b,a)=>Ta(a),O:Va,N:null},sb=(b,a)=>{switch(a){case 4:return function(c){return this.H(ka[c>>2])};case 8:return function(c){return this.H(la[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},tb=Object.assign({optional:!0},rb),ub="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,vb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},wb=(b=0,a)=>{var c=B;a=vb(c,b,a,!0);if(16<a-b&&c.buffer&&ub)return ub.decode(c.subarray(b,a));for(var d="";b<a;){var e=c[b++];if(e&128){var f=c[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=c[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|c[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
xb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,yb=(b,a,c)=>{b>>=1;a=vb(E,b,a/2,c);if(16<a-b&&xb)return xb.decode(E.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(E[b]);return c},zb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)C[a>>1]=b.charCodeAt(e),a+=2;C[a>>1]=0;return a-d},Ab=b=>2*b.length,Bb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var f=G[b+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},
Cb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;F[a>>2]=f;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},Db=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Eb=[],Fb=b=>{var a=Eb.length;Eb.push(b);return a},Gb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d){var e=d,f=G[a+4*d>>2],h=N[f];if(void 0===h)throw b=`${`parameter ${d}`} has unknown type ${hb(f)}`,new P(b);c[e]=h}return c},Hb=(b,a,c)=>{var d=[];b=b(d,
c);d.length&&(G[a>>2]=Ta(d));return b},Ib={},Jb=b=>{var a=Ib[b];return void 0===a?L(b):a};
(()=>{let b=S.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof S&&c instanceof S))return!1;var d=this.C.G.D,e=this.C.F;c.C=c.C;var f=c.C.G.D;for(c=c.C.F;d.K;)e=d.W(e),d=d.K;for(;f.K;)c=f.W(c),f=f.K;return d===f&&e===c},clone:function(){this.C.F||Ga(this);if(this.C.V)return this.C.count.value+=1,this;var c=R,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.C;c=c(e.call(d,f,{C:{value:{count:h.count,U:h.U,V:h.V,F:h.F,G:h.G,J:h.J,M:h.M}}}));c.C.count.value+=1;c.C.U=!1;return c},
["delete"](){this.C.F||Ga(this);if(this.C.U&&!this.C.V)throw new P("Object already scheduled for deletion");Ia(this);var c=this.C;--c.count.value;0===c.count.value&&(c.J?c.M.R(c.J):c.G.D.R(c.F));this.C.V||(this.C.J=void 0,this.C.F=void 0)},isDeleted:function(){return!this.C.F},deleteLater:function(){this.C.F||Ga(this);if(this.C.U&&!this.C.V)throw new P("Object already scheduled for deletion");Ja.push(this);this.C.U=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(ab.prototype,{ha(b){this.da&&(b=this.da(b));return b},aa(b){this.R?.(b)},O:Va,H:function(b){function a(){return this.Y?$a(this.D.P,{G:this.ja,F:c,M:this,J:b}):$a(this.D.P,{G:this,F:b})}var c=this.ha(b);if(!c)return this.aa(b),null;var d=Ya(this.D,c);if(void 0!==d){if(0===d.C.count.value)return d.C.F=c,d.C.J=b,d.clone();d=d.clone();this.aa(b);return d}d=this.D.ga(c);d=La[d];if(!d)return a.call(this);d=this.X?d.ea:d.pointerType;var e=Wa(c,this.D,d.D);return null===e?a.call(this):this.Y?
$a(d.D.P,{G:d,F:e,M:this,J:b}):$a(d.D.P,{G:d,F:e})}});k.noExitRuntime&&(za=k.noExitRuntime);k.printErr&&(z=k.printErr);k.wasmBinary&&(A=k.wasmBinary);
var fb,Kb,Lb,V,Mb={l:(b,a,c)=>{var d=new Aa(b);G[d.F+16>>2]=0;G[d.F+4>>2]=a;G[d.F+8>>2]=c;Ba=b;Ca++;throw Ba;},p:()=>oa(""),o:(b,a,c,d,e)=>{a=L(a);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}Q(b,{name:a,H:f,L:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},O:Fa(a,c,!d),N:null})},t:(b,a,c,d)=>{a=L(a);Q(b,{name:a,H:function(e){return!!e},L:function(e,f){return f?c:d},O:function(e){return this.H(B[e])},N:null})},f:(b,a,c,d,e,f,h,g,l,n,m,u,w)=>{m=L(m);f=U(e,f);g&&=U(h,g);
n&&=U(l,n);w=U(u,w);var r=Oa(m);Na(r,function(){W(`Cannot construct ${m} due to unbound types`,[d])});X([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.D;var H=x.P}else H=S.prototype;v=Ka(m,function(...ya){if(Object.getPrototypeOf(this)!==I)throw new P(`Use 'new' to construct ${m}`);if(void 0===y.S)throw new P(`${m} has no accessible constructor`);var gb=y.S[ya.length];if(void 0===gb)throw new P(`Tried to invoke ctor of ${m} with invalid number of parameters (${ya.length}) - expected (${Object.keys(y.S).toString()}) parameters instead!`);
return gb.apply(this,ya)});var I=Object.create(H,{constructor:{value:v}});v.prototype=I;var y=new Pa(m,v,I,w,x,f,g,n);if(y.K){var D;(D=y.K).$??(D.$=[]);y.K.$.push(y)}x=new ab(m,y,!0,!1,!1);D=new ab(m+"*",y,!1,!1,!1);H=new ab(m+" const*",y,!1,!0,!1);La[b]={pointerType:D,ea:H};bb(r,v);return[x,D,H]})},c:(b,a,c,d,e,f)=>{var h=ib(a,c);e=U(d,e);X([],[b],g=>{g=g[0];var l=`constructor ${g.name}`;void 0===g.D.S&&(g.D.S=[]);if(void 0!==g.D.S[a-1])throw new P(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.D.S[a-1]=()=>{W(`Cannot construct ${g.name} due to unbound types`,h)};X([],h,n=>{n.splice(1,0,null);g.D.S[a-1]=lb(l,n,null,e,f);return[]});return[]})},a:(b,a,c,d,e,f,h,g,l)=>{var n=ib(c,d);a=L(a);a=mb(a);f=U(e,f);X([],[b],m=>{function u(){W(`Cannot call ${w} due to unbound types`,n)}m=m[0];var w=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);g&&m.D.ka.push(a);
var r=m.D.P,v=r[a];void 0===v||void 0===v.I&&v.className!==m.name&&v.T===c-2?(u.T=c-2,u.className=m.name,r[a]=u):(Ma(r,a,w),r[a].I[c-2]=u);X([],n,x=>{x=lb(w,x,m,f,h,l);void 0===r[a].I?(x.T=c-2,r[a]=x):r[a].I[c-2]=x;return[]});return[]})},b:(b,a,c,d,e,f,h,g,l,n)=>{a=L(a);e=U(d,e);X([],[b],m=>{m=m[0];var u=`${m.name}.${a}`,w={get(){W(`Cannot access ${u} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};w.set=l?()=>W(`Cannot access ${u} due to unbound types`,[c,h]):()=>{throw new P(u+" is a read-only property");
};Object.defineProperty(m.D.P,a,w);X([],l?[c,h]:[c],r=>{var v=r[0],x={get(){var I=nb(this,m,u+" getter");return v.H(e(f,I))},enumerable:!0};if(l){l=U(g,l);var H=r[1];x.set=function(I){var y=nb(this,m,u+" setter"),D=[];l(n,y,H.L(D,I));jb(D)}}Object.defineProperty(m.D.P,a,x);return[]});return[]})},r:b=>Q(b,rb),n:(b,a,c)=>{a=L(a);Q(b,{name:a,H:d=>d,L:(d,e)=>e,O:sb(a,c),N:null})},e:(b,a,c,d,e,f,h)=>{var g=ib(a,c);b=L(b);b=mb(b);e=U(d,e);Na(b,function(){W(`Cannot call ${b} due to unbound types`,g)},a-
1);X([],g,l=>{l=[l[0],null].concat(l.slice(1));bb(b,lb(b,l,null,e,f,h),a-1);return[]})},g:(b,a,c,d,e)=>{a=L(a);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}Q(b,{name:a,H:f,L:(g,l)=>l,O:Fa(a,c,0!==d),N:null})},d:(b,a,c)=>{function d(f){return new e(ja.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=L(c);Q(b,{name:c,H:d,O:d},{ia:!0})},k:b=>{Q(b,tb)},s:(b,a)=>{a=L(a);Q(b,{name:a,
H(c){var d=(d=c+4)?wb(d,G[c>>2]):"";V(c);return d},L(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new P("Cannot pass non-string to std::string");var h;if(f)for(e=h=0;e<d.length;++e){var g=d.charCodeAt(e);127>=g?h++:2047>=g?h+=2:55296<=g&&57343>=g?(h+=4,++e):h+=3}else h=d.length;e=h;h=Kb(4+e+1);g=h+4;G[h>>2]=e;if(f){if(f=g,g=e+1,e=B,0<g){g=f+g-1;for(var l=0;l<d.length;++l){var n=d.codePointAt(l);if(127>=
n){if(f>=g)break;e[f++]=n}else if(2047>=n){if(f+1>=g)break;e[f++]=192|n>>6;e[f++]=128|n&63}else if(65535>=n){if(f+2>=g)break;e[f++]=224|n>>12;e[f++]=128|n>>6&63;e[f++]=128|n&63}else{if(f+3>=g)break;e[f++]=240|n>>18;e[f++]=128|n>>12&63;e[f++]=128|n>>6&63;e[f++]=128|n&63;l++}}e[f]=0}}else B.set(d,g);null!==c&&c.push(V,h);return h},O:Va,N(c){V(c)}})},m:(b,a,c)=>{c=L(c);if(2===a){var d=yb;var e=zb;var f=Ab}else d=Bb,e=Cb,f=Db;Q(b,{name:c,H:h=>{var g=d(h+4,G[h>>2]*a,!0);V(h);return g},L:(h,g)=>{if("string"!=
typeof g)throw new P(`Cannot pass non-string to C++ string type ${c}`);var l=f(g),n=Kb(4+l+a);G[n>>2]=l/a;e(g,n+4,l+a);null!==h&&h.push(V,n);return n},O:Va,N(h){V(h)}})},u:(b,a)=>{a=L(a);Q(b,{ba:!0,name:a,H:()=>{},L:()=>{}})},j:(b,a,c)=>{var [d,...e]=Gb(b,a);a=d.L.bind(d);var f=e.map(l=>l.O.bind(l));b--;var h={toValue:qb};b=f.map((l,n)=>{var m=`argFromPtr${n}`;h[m]=l;return`${m}(args${n?"+"+8*n:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g=
"";break;case 1:h.getStringOrSymbol=Jb,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${b})`;d.ba||(h.toReturnWire=a,h.emval_returnValue=Hb,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n  ${g}\n  }`;c=(new Function(Object.keys(h),g))(...Object.values(h));g=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return Fb(Ka(g,c))},i:(b,a,c,d,e)=>Eb[b](a,c,d,e),h:b=>{var a=qb(b);jb(a);pb(b)},q:()=>{oa("OOM")}},
Z;
(async function(){function b(c){Z=c.exports;ia=Z.v;c=ia.buffer;ja=new Int8Array(c);C=new Int16Array(c);B=new Uint8Array(c);E=new Uint16Array(c);F=new Int32Array(c);G=new Uint32Array(c);ka=new Float32Array(c);la=new Float64Array(c);ma=new BigInt64Array(c);na=new BigUint64Array(c);db=Z.y;c=Z;fb=c.x;Kb=c.z;k._main=Lb=c.A;V=c.B;J--;k.monitorRunDependencies?.(J);0==J&&K&&(c=K,K=null,c());return Z}J++;k.monitorRunDependencies?.(J);var a={a:Mb};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(a,(d,
e)=>{c(b(d,e))})});pa??=k.locateFile?k.locateFile("immolate.wasm",p):p+"immolate.wasm";return b((await sa(a)).instance)})();
function Nb(){function b(){k.calledRun=!0;if(!ha){Z.w();k.onRuntimeInitialized?.();if(!k.noInitialRun){var a=Lb;try{var c=a(0,0);za||(k.onExit?.(c),ha=!0);da(c,new ta(c))}catch(d){d instanceof ta||"unwind"==d||da(1,d)}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)a=k.postRun.shift(),va.push(a);ua(va)}}if(0<J)K=Nb;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)xa();ua(wa);0<J?K=Nb:k.setStatus?(k.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);b()},1)):b()}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();Nb();
